### ISSUE TITLE
the zabbix_alerta.py is not running

### ISSUE THREAD

**Issue by lynch0227** [alerta/zabbix-alerta#1]
The zabbix server and alerta server is not in the same server.
I configure the zabbix follow your steps, and there is one trigger has been issued.
But I find there is nothing in zabbix_alerta.log file.
That seems the zabbix_alerta.py script has never been ran.
Do I need to install alerta-cli in zabbix server?

**Comment by satterly** [comment]
No, you don't need the `alerta-cli` tool installed but you do need python `requests` package. You could either use `sudo pip install requests` or `sudo apt-get install python-requests` (on debian). Alternatively you could install the `alerta-cli` on the zabbix server as that would then install requests for you.

I found it very difficult to get the Zabbix configuration right so that the `zabbix_alerta.py` would be called when an alert was generated or acknowledged by Zabbix. Are there any messages in `/var/log/zabbix/zabbix_alerta.log`? Does that directory exist? Try touching that file and make it world writable ie. `chmod 777 /var/log/zabbix/zabbix_alerta.log`.

Lastly, review your configuration steps using the PagerDuty integration guide [here](https://www.pagerduty.com/docs/guides/zabbix-integration-guide/) and let me know if it still isn't working.

**Comment by lynch0227** [comment]
I have installed the request package.
root@mqtt:~# python
Python 2.7.3 (default, Jun 22 2015, 19:33:41) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import requests;

I have modified the log_file path in zabbix_alerta.py file.
........
**version** = '3.1.0'

LOG_FILE = '/usr/local/zabbix/log/zabbix_alerta.log'
..........

I already have create zabbix_alerta.log file, and chmod 666  for it.
But I still can't get any message from that log.
root@xxx:/usr/local/zabbix/log# ll
total 1408
drwxrwxr-x  2 zabbix zabbix    4096 Jul  9 20:33 ./
drwxr-xr-x 11 zabbix zabbix    4096 Jul  9 17:46 ../
-rw-rw-r--  1 root   root    121825 Jul  9 20:36 zabbix_agentd.log
-rw-rw-rw-  1 zabbix zabbix       0 Jul  9 20:06 zabbix_alerta.log
-rw-rw-r--  1 zabbix zabbix  251826 Jul  9 21:56 zabbix_server.log

**Comment by satterly** [comment]
e8c287654d7a0a668fd0989e3bd90ba451d32ff0 should fix the issue of no output appearing in the log file. However, if Zabbix isn't configured correctly then there's a chance the script isn't be run at all. Try updating the script and double-checking your config again.

BTW, I just tested this script and the configuration instructions again using the [alerta-zabbix](https://github.com/alerta/vagrant-try-alerta) Vagrant box and it worked fine for me.

**Comment by satterly** [comment]
<img width="1561" alt="screen shot 2015-07-09 at 22 08 46" src="https://cloud.githubusercontent.com/assets/615057/8606921/233a50f4-2687-11e5-97bc-75eded57f4af.png">

**Comment by satterly** [comment]
Oh, and please open a new issue if you're still having problems.
